# This is a basic workflow to help you get started with Actions
name: Continuos Integration

# Controls when the workflow will run
on: push

jobs: 
  # This workflow contains a single job called "build"
  continuos-integration:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: action/checkout@v3

      - name: install dependencies
        run: npm install
